name: theme_preferences_app
description: A Flutter app to demonstrate theme preferences using shared preferences.

publish_to: 'none' # Remove this line if you want to publish to pub.dev

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.11  # Check for the latest version

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
